version: "3.6"

services:

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/phpunit-property-based-testing
    working_dir: /var/www/phpunit-property-based-testing

  composer:
    image: composer:1.6