version: '3'

services:

  node:
    build:
      context: ./docker/node
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    working_dir: /home/node/app
    entrypoint: ./docker/node/scripts/entrypoint.sh
    environment:
      - NODE_ENV=development
      - PORT=8081
