version: "3"

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/phpspec-tdd-baby-steps
    working_dir: /var/www/phpspec-tdd-baby-steps

  composer:
    image: composer:1.6